from enum import Enum


class HttpStatus(Enum):
    # INFORMATION RESPONSES
    CONTINUE = 100

    # SUCCESSFUL RESPONSES
    OK = 200

    # REDIRECTION MESSAGES
    MOVED_PERMANENTLY = 301

    # CLIENT ERROR RESPONSES
    NOT_FOUND = 404

    # SERVER ERROR RESPONSES
    INTERNAL_SERVER_ERROR = 500
